In [48]:
import pandas as pd

df = pd.read_csv("gdelt_news1.csv")

In [49]:
df.head()

,commodity,country,keyword,title,date,source,url,language
0,Wheat,India,import,"पर्सामा गहुँ उत्पादन घट्यो , भारतबाट आयात बढ्यो",20260526T130000Z,ekantipur.com,https://ekantipur.com/business/2026/05/26/whea...,Nepali
1,Wheat,India,import,भारतासमोर मोठे संकट ? खाद्यतेलाचा प्रचंड तुटवड...,20260514T054500Z,loksatta.com,https://www.loksatta.com/explained/india-edibl...,Marathi
2,Wheat,India,import,印度有多缺油 食用油危机凸显 _ 军事频道 _ 中华网,20260521T041500Z,military.china.com,https://military.china.com/news/13004177/20260...,Chinese
3,Wheat,India,import,ബഗ്ലിഹാർ അടച്ചിട്ടിട്ട് ഒരു വർഷം : ജലയുദ്ധത്തി...,20260503T134500Z,madhyamam.com,https://www.madhyamam.com/world/baglihar-remai...,Malayalam
4,Wheat,India,import,"Tarımda ithalat faturası : Patates depoda , po...",20260511T071500Z,odatv.com,https://www.odatv.com/ekonomi/tarimda-ithalat-...,Turkish

In [50]:
df.describe()

,commodity,country,keyword,title,date,source,url,language
count,1816,1816,1816,1816,1816,1816,1816,1816
unique,8,13,4,1310,1138,650,1442,33
top,Soybean,Netherlands,demand,"LensTalk | Sri Lanka : A Leafy Scent , a Hills...",20260508T233000Z,finance.eastmoney.com,https://www.rfdtv.com/plant26-iowa-farmers-pla...,English
freq,311,200,617,18,10,57,10,625

In [51]:
df = df[
[
    "commodity",
    "country",
    "title",
    "language",
    "date",
    "source",
    "url"
]
]

In [52]:
from deep_translator import GoogleTranslator

translator = GoogleTranslator(
    source="auto",
    target="en"
)

In [53]:
def translate(text):

    if pd.isna(text):
        return ""

    try:
        return translator.translate(str(text))

    except:
        return str(text)

In [ ]:
df["title_english"] = df["title"].apply(translate)

In [ ]:
df["title_english"].head()

0    India lifts total wheat export quota to 5 mill...
1    India move to export 5 mt wheat unlikely to im...
2    India set to double wheat , flour export quota...
3    Geopolitical crisis , weather may help India e...
4    India resumes wheat exports after four years, ...
Name: title_english, dtype: str

In [ ]:
news_ml_dataset1 = pd.DataFrame(df)

news_ml_dataset1.to_csv("news_ml_dataset1.csv", index=False)

print(news_ml_dataset1.head())

  commodity country                                              title  \
0     Wheat   India  India lifts total wheat export quota to 5 mill...
1     Wheat   India  India move to export 5 mt wheat unlikely to im...
2     Wheat   India  India set to double wheat , flour export quota...
3     Wheat   India  Geopolitical crisis , weather may help India e...
4     Wheat   India  LInde reprend ses exportations de blé après qu...

  language  date                        source  \
0  English   NaN  economictimes.indiatimes.com
1  English   NaN      thehindubusinessline.com
2  English   NaN                  livemint.com
3  English   NaN      thehindubusinessline.com
4   French   NaN                zonebourse.com

                                                 url  \
0  https://economictimes.indiatimes.com/small-biz...
1  https://www.thehindubusinessline.com/economy/a...
2  https://www.livemint.com/news/wheat-atta-expor...
3  https://www.thehindubusinessline.com/economy/a...
4  https://www.zonebourse.com/actualite-bourse/l-...

                                       title_english
0  India lifts total wheat export quota to 5 mill...
1  India move to export 5 mt wheat unlikely to im...
2  India set to double wheat , flour export quota...
3  Geopolitical crisis , weather may help India e...
4  India resumes wheat exports after four years, ...

In [ ]:
from groq import Groq

client = Groq(
    #base_url="https://api.groq.com/openai/v1",
    api_key="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"
)

#MODEL = "llama-3.3-70b-versatile"
MODEL = "llama-3.1-8b-instant"

In [ ]:
def analyze_news(title):

    prompt = f"""
You are an Agricultural Export Intelligence Analyst.

The following news headline is already translated into English.

Your task is to determine whether this news creates an export opportunity for India.

Return ONLY valid JSON.

{{
    # "summary":"",

    # "event_type":"",

    # "demand_signal":"",

    # "demand_reason":"",

    # "market_impact":"",

    # "recommended_action":"",

    # "sentiment":"",

    # "sentiment_score":0,

    # "import_flag":0,

    # "export_flag":0,

    # "shortage_flag":0,

    # "production_drop":0,

    # "production_rise":0,

    # "price_increase":0,

    # "price_decrease":0,

    # "government_policy":0,

    # "weather_event":0,

    # "trade_issue":0,

    # "food_security_issue":0,

    # "export_opportunity_score":0,

    # "confidence":0



    "summary":"",
    "event_type":"",
    "demand_signal":"",
    "demand_reason":"",
    "market_impact":"",
    "recommended_action":"",
    "sentiment":"",
    "sentiment_score":0,
    "import_flag":0,
    "export_flag":0,
    "shortage_flag":0,
    "production_drop":0,
    "production_rise":0,
    "price_increase":0,
    "price_decrease":0,
    "government_policy":0,
    "weather_event":0,
    "trade_issue":0,
    "food_security_issue":0,
    "export_opportunity_score":0,
    "confidence":0
}}

Rules

Summary:
One sentence only.

Event Type should be ONE of

Import Increase

Import Restriction

Export Increase

Export Restriction

Production Drop

Production Rise

Government Policy

Weather Disaster

Food Shortage

Price Rise

Price Fall

Trade Agreement

Conflict

Disease

Other

Demand Signal

High

Medium

Low

Neutral

Market Impact

Positive for Indian Exporters

Negative for Indian Exporters

Neutral

Recommended Action examples

Export Wheat to Egypt

Export Rice to Bangladesh

Export Sugar to Indonesia

No Immediate Action

Sentiment

Positive

Neutral

Negative

Sentiment Score

Between -1 and 1

Export Opportunity Score

0 to 100

Confidence

0 to 1

Flags

Only 0 or 1

Headline

{title}

Return ONLY JSON.
"""

    response = client.chat.completions.create(

        model=MODEL,

        temperature=0,

        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    text = response.choices[0].message.content

    text = text.replace("```json","")
    text = text.replace("```","")

    return json.loads(text)

In [ ]:
import json
sample = analyze_news(df.iloc[0]["title_english"])

print(json.dumps(sample, indent=4))

{
    "summary": "India lifts total wheat export quota to 5 million tons",
    "event_type": "Export Increase",
    "demand_signal": "High",
    "demand_reason": "Government Policy",
    "market_impact": "Positive for Indian Exporters",
    "recommended_action": "Export Wheat to Egypt",
    "sentiment": "Positive",
    "sentiment_score": 0.8,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 0,
    "price_decrease": 0,
    "government_policy": 1,
    "weather_event": 0,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 80,
    "confidence": 0.9
}

In [ ]:
for i in range(5):

    print("="*80)

    print(df.iloc[i]["title_english"])

    print()

    result = analyze_news(df.iloc[i]["title_english"])

    print(json.dumps(result, indent=4))

================================================================================
India lifts total wheat export quota to 5 million tons

{
    "summary": "India lifts total wheat export quota to 5 million tons",
    "event_type": "Export Increase",
    "demand_signal": "High",
    "demand_reason": "Government Policy",
    "market_impact": "Positive for Indian Exporters",
    "recommended_action": "Export Wheat to Egypt",
    "sentiment": "Positive",
    "sentiment_score": 0.8,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 0,
    "price_decrease": 0,
    "government_policy": 1,
    "weather_event": 0,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 80,
    "confidence": 0.9
}
================================================================================
India move to export 5 mt wheat unlikely to impact global market

{
    "summary": "India move to export 5 mt wheat unlikely to impact global market",
    "event_type": "Export Increase",
    "demand_signal": "High",
    "demand_reason": "Government Policy",
    "market_impact": "Neutral",
    "recommended_action": "Export Wheat to Egypt",
    "sentiment": "Positive",
    "sentiment_score": 0.8,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 0,
    "price_decrease": 0,
    "government_policy": 1,
    "weather_event": 0,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 80,
    "confidence": 0.9
}
================================================================================
India set to double wheat , flour export quota to tap global price spurt

{
    "summary": "India set to double wheat, flour export quota to tap global price spurt",
    "event_type": "Export Increase",
    "demand_signal": "High",
    "demand_reason": "Global price spurt",
    "market_impact": "Positive for Indian Exporters",
    "recommended_action": "Export Wheat to Egypt, Export Wheat to Bangladesh",
    "sentiment": "Positive",
    "sentiment_score": 0.8,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 1,
    "price_decrease": 0,
    "government_policy": 1,
    "weather_event": 0,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 80,
    "confidence": 0.9
}
================================================================================
Geopolitical crisis , weather may help India export 2 mt of wheat , says USDA

{
    "summary": "Geopolitical crisis, weather may help India export 2 mt of wheat, says USDA",
    "event_type": "Export Increase",
    "demand_signal": "High",
    "demand_reason": "Geopolitical crisis",
    "market_impact": "Positive for Indian Exporters",
    "recommended_action": "Export Wheat to Egypt",
    "sentiment": "Positive",
    "sentiment_score": 0.8,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 0,
    "price_decrease": 0,
    "government_policy": 0,
    "weather_event": 1,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 80,
    "confidence": 0.9
}
================================================================================
India resumes wheat exports after four years, but high prices expected to limit demand

{
    "summary": "India resumes wheat exports after four years, but high prices expected to limit demand",
    "event_type": "Export Increase",
    "demand_signal": "Low",
    "demand_reason": "High prices expected to limit demand",
    "market_impact": "Negative for Indian Exporters",
    "recommended_action": "No Immediate Action",
    "sentiment": "Neutral",
    "sentiment_score": 0,
    "import_flag": 0,
    "export_flag": 1,
    "shortage_flag": 0,
    "production_drop": 0,
    "production_rise": 0,
    "price_increase": 1,
    "price_decrease": 0,
    "government_policy": 0,
    "weather_event": 0,
    "trade_issue": 0,
    "food_security_issue": 0,
    "export_opportunity_score": 20,
    "confidence": 0.5
}

In [ ]:
import time
import pandas as pd
from tqdm import tqdm

In [ ]:
rows = []

In [ ]:
for index, row in tqdm(df.iterrows(), total=len(df)):

    try:

        result = analyze_news(row["title_english"])

        rows.append({

            "commodity": row["commodity"],

            "country": row["country"],

            "date": row["date"],

            "language": row["language"],

            "source": row["source"],

            "url": row["url"],

            "title_original": row["title"],

            "title_english": row["title_english"],

            "summary": result["summary"],

            "event_type": result["event_type"],

            "demand_signal": result["demand_signal"],

            "demand_reason": result["demand_reason"],

            "market_impact": result["market_impact"],

            "recommended_action": result["recommended_action"],

            "sentiment": result["sentiment"],

            "sentiment_score": result["sentiment_score"],

            "import_flag": result["import_flag"],

            "export_flag": result["export_flag"],

            "shortage_flag": result["shortage_flag"],

            "production_drop": result["production_drop"],

            "production_rise": result["production_rise"],

            "price_increase": result["price_increase"],

            "price_decrease": result["price_decrease"],

            "government_policy": result["government_policy"],

            "weather_event": result["weather_event"],

            "trade_issue": result["trade_issue"],

            "food_security_issue": result["food_security_issue"],

            "export_opportunity_score": result["export_opportunity_score"],

            "confidence": result["confidence"]

        })

    except Exception as e:

        print(f"Error at row {index}: {e}")

        continue

    time.sleep(5)

 11%|█         | 103/956 [11:59<1:09:06,  4.86s/it]

Error at row 102: Extra data: line 25 column 1 (char 692)

 26%|██▌       | 247/956 [30:12<1:08:22,  5.79s/it]

Error at row 246: Extra data: line 25 column 1 (char 594)

 27%|██▋       | 254/956 [31:05<1:10:50,  6.05s/it]

Error at row 253: Extra data: line 25 column 1 (char 680)

 27%|██▋       | 257/956 [31:29<1:15:42,  6.50s/it]

Error at row 256: Extra data: line 25 column 1 (char 689)

 28%|██▊       | 269/956 [32:57<1:11:37,  6.26s/it]

Error at row 268: Extra data: line 25 column 1 (char 621)

 28%|██▊       | 271/956 [33:13<1:16:58,  6.74s/it]

Error at row 270: Extra data: line 25 column 1 (char 597)

 30%|██▉       | 286/956 [35:10<1:12:05,  6.46s/it]

Error at row 285: Extra data: line 25 column 1 (char 701)

 30%|███       | 289/956 [35:33<1:14:07,  6.67s/it]

Error at row 288: Extra data: line 25 column 1 (char 612)

 34%|███▎      | 321/956 [39:19<59:24,  5.61s/it]

Error at row 320: Extra data: line 25 column 1 (char 635)

 37%|███▋      | 351/956 [43:10<1:01:43,  6.12s/it]

Error at row 350: Extra data: line 25 column 1 (char 709)

 39%|███▊      | 369/956 [45:20<54:41,  5.59s/it]

Error at row 368: Extra data: line 25 column 1 (char 718)

 39%|███▉      | 377/956 [46:21<58:50,  6.10s/it]

Error at row 376: Extra data: line 25 column 1 (char 623)

 44%|████▍     | 420/956 [1:01:29<53:44,  6.02s/it]

Error at row 419: Extra data: line 25 column 1 (char 725)

 47%|████▋     | 448/956 [1:05:06<53:10,  6.28s/it]

Error at row 447: Extra data: line 25 column 1 (char 633)

 47%|████▋     | 451/956 [1:05:30<55:20,  6.58s/it]

Error at row 450: Extra data: line 25 column 1 (char 668)

 57%|█████▋    | 544/956 [1:16:56<43:39,  6.36s/it]

Error at row 543: Extra data: line 25 column 1 (char 654)

 58%|█████▊    | 552/956 [1:17:50<34:45,  5.16s/it]

Error at row 551: Extra data: line 25 column 1 (char 619)

 62%|██████▏   | 589/956 [1:22:19<36:38,  5.99s/it]

Error at row 588: Extra data: line 25 column 1 (char 653)

 62%|██████▏   | 595/956 [1:23:07<44:16,  7.36s/it]

Error at row 594: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5398, Requested 812. Please try again in 2.1s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 600/956 [1:24:08<1:22:12, 13.86s/it]

Error at row 599: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5198, Requested 841. Please try again in 389.999999ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 601/956 [1:24:21<1:19:03, 13.36s/it]

Error at row 600: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5365, Requested 832. Please try again in 1.97s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 602/956 [1:24:30<1:11:21, 12.09s/it]

Error at row 601: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5109, Requested 1965. Please try again in 10.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 603/956 [1:24:41<1:10:10, 11.93s/it]

Error at row 602: Extra data: line 25 column 1 (char 603)

 63%|██████▎   | 605/956 [1:25:36<1:56:15, 19.87s/it]

Error at row 604: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5617, Requested 2626. Please try again in 22.43s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 606/956 [1:25:58<2:00:00, 20.57s/it]

Error at row 605: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5761, Requested 2612. Please try again in 23.73s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 63%|██████▎   | 607/956 [1:26:34<2:26:53, 25.25s/it]

Error at row 606: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 4532, Requested 2561. Please try again in 10.93s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▎   | 608/956 [1:27:10<2:43:41, 28.22s/it]

Error at row 607: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5845, Requested 2587. Please try again in 24.32s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▎   | 609/956 [1:27:48<3:00:25, 31.20s/it]

Error at row 608: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5755, Requested 2613. Please try again in 23.68s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 610/956 [1:28:37<3:31:01, 36.59s/it]

Error at row 609: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5697, Requested 2615. Please try again in 23.12s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 611/956 [1:29:25<3:50:22, 40.06s/it]

Error at row 610: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5730, Requested 2615. Please try again in 23.45s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 612/956 [1:30:10<3:58:27, 41.59s/it]

Error at row 611: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5889, Requested 2579. Please try again in 24.68s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 613/956 [1:30:58<4:08:59, 43.56s/it]

Error at row 612: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5839, Requested 2610. Please try again in 24.49s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 614/956 [1:31:47<4:17:53, 45.24s/it]

Error at row 613: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5525, Requested 2623. Please try again in 21.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 615/956 [1:32:34<4:18:48, 45.54s/it]

Error at row 614: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5224, Requested 2607. Please try again in 18.31s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 64%|██████▍   | 616/956 [1:33:17<4:14:03, 44.83s/it]

Error at row 615: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5546, Requested 2628. Please try again in 21.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 65%|██████▍   | 617/956 [1:34:04<4:17:20, 45.55s/it]

Error at row 616: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5819, Requested 2623. Please try again in 24.42s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 65%|██████▍   | 618/956 [1:34:45<4:09:19, 44.26s/it]

Error at row 617: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5703, Requested 2618. Please try again in 23.209999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 65%|██████▍   | 619/956 [1:35:33<4:13:27, 45.13s/it]

Error at row 618: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5766, Requested 2600. Please try again in 23.66s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 65%|██████▍   | 620/956 [1:36:21<4:17:52, 46.05s/it]

Error at row 619: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per minute (TPM): Limit 6000, Used 5226, Requested 2623. Please try again in 18.49s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 65%|██████▌   | 625/956 [1:36:40<1:17:15, 14.00s/it]

Error at row 620: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 2609. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 621: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 2608. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 622: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 2635. Please try again in 6m51.7824s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 623: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 2612. Please try again in 6m47.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 624: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499748, Requested 2618. Please try again in 6m48.8448s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 625: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499747, Requested 2615. Please try again in 6m48.1536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 626: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499747, Requested 2615. Please try again in 6m48.1536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 627: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499747, Requested 2611. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 66%|██████▌   | 633/956 [1:36:40<23:43,  4.41s/it]

Error at row 628: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499747, Requested 2602. Please try again in 6m45.9072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 629: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499747, Requested 2613. Please try again in 6m47.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 630: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2624. Please try again in 6m49.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 631: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2643. Please try again in 6m52.8192s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 632: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2606. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 633: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2612. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 634: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2612. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 635: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2621. Please try again in 6m49.0176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 67%|██████▋   | 641/956 [1:36:40<09:43,  1.85s/it]

Error at row 636: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499746, Requested 2619. Please try again in 6m48.671999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 637: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2624. Please try again in 6m49.3632s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 638: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2623. Please try again in 6m49.190399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 639: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2614. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 640: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2634. Please try again in 6m51.0912s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 641: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2606. Please try again in 6m46.2528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 642: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499745, Requested 2616. Please try again in 6m47.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 643: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2638. Please try again in 6m51.6096s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 644: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2613. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 68%|██████▊   | 650/956 [1:36:41<04:09,  1.23it/s]

Error at row 645: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2630. Please try again in 6m50.2272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 646: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2611. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 647: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2617. Please try again in 6m47.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 648: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2613. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 649: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499744, Requested 2611. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 650: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2616. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 651: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2604. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 652: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2617. Please try again in 6m47.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 653: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2609. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 69%|██████▉   | 662/956 [1:36:41<01:26,  3.39it/s]

Error at row 654: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2618. Please try again in 6m47.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 655: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499743, Requested 2613. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 656: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2630. Please try again in 6m49.8816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 657: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2617. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 658: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2603. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 659: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2624. Please try again in 6m48.8448s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 660: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2606. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 661: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2610. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 70%|██████▉   | 667/956 [1:36:41<00:57,  4.99it/s]

Error at row 662: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499742, Requested 2614. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 663: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2624. Please try again in 6m48.671999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 664: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2622. Please try again in 6m48.3264s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 665: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2610. Please try again in 6m46.2528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 666: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2607. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 667: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2604. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 668: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2609. Please try again in 6m46.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 669: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2636. Please try again in 6m50.7456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 71%|███████   | 676/956 [1:36:41<00:31,  9.03it/s]

Error at row 670: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499741, Requested 2614. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 671: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2605. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 672: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2613. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 673: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2636. Please try again in 6m50.5728s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 674: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2606. Please try again in 6m45.3888s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 675: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2609. Please try again in 6m45.9072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 676: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499740, Requested 2627. Please try again in 6m49.0176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 677: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2614. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 678: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2609. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 72%|███████▏  | 684/956 [1:36:41<00:18, 14.48it/s]

Error at row 679: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2608. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 680: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2619. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 681: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2615. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 682: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2611. Please try again in 6m46.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 683: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499739, Requested 2608. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 684: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2603. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 685: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2611. Please try again in 6m45.9072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 686: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2601. Please try again in 6m44.1792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 687: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2605. Please try again in 6m44.8704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 72%|███████▏  | 693/956 [1:36:42<00:11, 21.92it/s]

Error at row 688: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2616. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 689: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2608. Please try again in 6m45.3888s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 690: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499738, Requested 2619. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 691: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2616. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 692: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2615. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 693: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2625. Please try again in 6m48.1536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 694: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2613. Please try again in 6m46.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 695: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2641. Please try again in 6m50.918399999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 73%|███████▎  | 701/956 [1:36:42<00:09, 27.73it/s]

Error at row 696: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499737, Requested 2619. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 697: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2619. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 698: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2634. Please try again in 6m49.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 699: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2611. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 700: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2623. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 701: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2608. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 702: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2619. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 703: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499736, Requested 2643. Please try again in 6m51.0912s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 704: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2606. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 74%|███████▍  | 710/956 [1:36:42<00:07, 32.75it/s]

Error at row 705: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2620. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 706: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2610. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 707: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2615. Please try again in 6m46.08s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 708: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2636. Please try again in 6m49.7088s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 709: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2610. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 710: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499735, Requested 2622. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 711: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2627. Please try again in 6m47.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 712: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2620. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 713: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2611. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 75%|███████▌  | 719/956 [1:36:42<00:06, 34.94it/s]

Error at row 714: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2647. Please try again in 6m51.4368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 715: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2619. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 716: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499734, Requested 2625. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 717: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2608. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 718: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2631. Please try again in 6m48.4992s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 719: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2623. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 720: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2626. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 721: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2621. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 722: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2611. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 76%|███████▋  | 729/956 [1:36:43<00:05, 38.48it/s]

Error at row 723: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499733, Requested 2611. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 724: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2626. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 725: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2612. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 726: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2608. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 727: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2609. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 728: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2616. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 729: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2610. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 730: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2615. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 731: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499732, Requested 2627. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 732: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2617. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 77%|███████▋  | 739/956 [1:36:43<00:05, 38.89it/s]

Error at row 733: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2623. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 734: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2621. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 735: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2603. Please try again in 6m43.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 736: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2613. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 737: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499731, Requested 2609. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 738: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2610. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 739: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2604. Please try again in 6m43.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 740: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2610. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 78%|███████▊  | 747/956 [1:36:43<00:05, 37.54it/s]

Error at row 741: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2602. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 742: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2606. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 743: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499730, Requested 2618. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 744: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2608. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 745: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2607. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 746: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2615. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 747: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2606. Please try again in 6m43.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 748: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2604. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 749: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2609. Please try again in 6m44.0064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 79%|███████▉  | 756/956 [1:36:43<00:05, 38.51it/s]

Error at row 750: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2607. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 751: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499729, Requested 2614. Please try again in 6m44.8704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 752: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2616. Please try again in 6m45.0432s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 753: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2613. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 754: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2609. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 755: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2609. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 756: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2605. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 80%|███████▉  | 764/956 [1:36:44<00:05, 34.50it/s]

Error at row 757: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499728, Requested 2629. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 758: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499727, Requested 2615. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 759: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499727, Requested 2609. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 760: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499727, Requested 2612. Please try again in 6m44.1792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 761: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499727, Requested 2614. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 762: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499727, Requested 2620. Please try again in 6m45.5616s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 763: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 2619. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 80%|████████  | 768/956 [1:36:44<00:05, 31.63it/s]

Error at row 764: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 2616. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 765: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 2605. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 766: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 2616. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 767: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499726, Requested 2633. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 768: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2631. Please try again in 6m47.1168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 769: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2620. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 770: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2607. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 81%|████████▏ | 777/956 [1:36:44<00:04, 36.50it/s]

Error at row 771: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2626. Please try again in 6m46.2528s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 772: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2618. Please try again in 6m44.8704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 773: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499725, Requested 2627. Please try again in 6m46.4256s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 774: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2610. Please try again in 6m43.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 775: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2608. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 776: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2637. Please try again in 6m47.9808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 777: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2621. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 778: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2604. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 82%|████████▏ | 785/956 [1:36:44<00:04, 34.75it/s]

Error at row 779: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2608. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 780: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499724, Requested 2616. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 781: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2612. Please try again in 6m43.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 782: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2611. Please try again in 6m43.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 783: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2626. Please try again in 6m45.9072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 784: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2649. Please try again in 6m49.8816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 785: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2626. Please try again in 6m45.9072s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 786: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499723, Requested 2609. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 83%|████████▎ | 793/956 [1:36:44<00:04, 34.25it/s]

Error at row 787: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 2620. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 788: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 2611. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 789: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 2614. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 790: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 2606. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 791: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499722, Requested 2610. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 792: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499721, Requested 2610. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 793: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499721, Requested 2610. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 84%|████████▍ | 801/956 [1:36:45<00:04, 31.70it/s]

Error at row 794: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499721, Requested 2601. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 795: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499721, Requested 2602. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 796: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499721, Requested 2615. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 797: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 2633. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 798: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 2639. Please try again in 6m47.6352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 799: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 2609. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 800: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 2617. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 84%|████████▍ | 805/956 [1:36:45<00:04, 31.54it/s]

Error at row 801: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499720, Requested 2619. Please try again in 6m44.1792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 802: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2626. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 803: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2622. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 804: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2616. Please try again in 6m43.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 805: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2609. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 806: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2624. Please try again in 6m44.8704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 85%|████████▌ | 813/956 [1:36:45<00:04, 30.88it/s]

Error at row 807: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499719, Requested 2629. Please try again in 6m45.7344s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 808: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499718, Requested 2654. Please try again in 6m49.8816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 809: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499718, Requested 2636. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 810: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499718, Requested 2639. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 811: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499718, Requested 2597. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 812: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499718, Requested 2614. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 86%|████████▌ | 823/956 [1:36:45<00:03, 37.27it/s]

Error at row 813: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2616. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 814: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2602. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 815: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2640. Please try again in 6m47.2896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 816: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2660. Please try again in 6m50.7456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 817: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2616. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 818: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2620. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 819: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499717, Requested 2611. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 820: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2638. Please try again in 6m46.7712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 821: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2644. Please try again in 6m47.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 822: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2608. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 87%|████████▋ | 828/956 [1:36:45<00:03, 39.69it/s]

Error at row 823: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2613. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 824: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2639. Please try again in 6m46.943999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 825: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2616. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 826: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2598. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 827: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499716, Requested 2613. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 828: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2630. Please try again in 6m45.215999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 829: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2601. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 830: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2607. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 831: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2622. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 88%|████████▊ | 838/956 [1:36:46<00:02, 42.35it/s]

Error at row 832: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2608. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 833: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2617. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 834: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2605. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 835: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499715, Requested 2614. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 836: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2605. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 837: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2610. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 838: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2610. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 839: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2618. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 840: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2618. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 841: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2612. Please try again in 6m41.9328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 89%|████████▊ | 848/956 [1:36:46<00:02, 40.85it/s]

Error at row 842: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499714, Requested 2617. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 843: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2602. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 844: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2615. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 845: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2607. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 846: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2607. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 847: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2614. Please try again in 6m42.1056s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 848: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2613. Please try again in 6m41.9328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 849: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499713, Requested 2606. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 850: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2612. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 90%|████████▉ | 858/956 [1:36:46<00:02, 40.62it/s]

Error at row 851: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2619. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 852: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2616. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 853: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2610. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 854: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2610. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 855: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2628. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 856: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499712, Requested 2615. Please try again in 6m42.1056s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 857: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2605. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 858: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2611. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 91%|█████████ | 867/956 [1:36:46<00:02, 39.47it/s]

Error at row 859: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2629. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 860: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2628. Please try again in 6m44.1792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 861: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2612. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 862: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2613. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 863: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499711, Requested 2649. Please try again in 6m47.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 864: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2610. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 865: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2608. Please try again in 6m40.5504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 866: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2606. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 91%|█████████ | 872/956 [1:36:47<00:02, 41.46it/s]

Error at row 867: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2606. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 868: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2606. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 869: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2609. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 870: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499710, Requested 2626. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 871: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2608. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 872: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2627. Please try again in 6m43.6608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 873: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2624. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 874: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2622. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 875: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2620. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 92%|█████████▏| 882/956 [1:36:47<00:01, 42.55it/s]

Error at row 876: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2633. Please try again in 6m44.697599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 877: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2623. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 878: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499709, Requested 2644. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 879: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2633. Please try again in 6m44.5248s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 880: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2635. Please try again in 6m44.8704s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 881: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2629. Please try again in 6m43.8336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 882: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2614. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 883: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2609. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 884: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2614. Please try again in 6m41.241599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 93%|█████████▎| 892/956 [1:36:47<00:01, 41.02it/s]

Error at row 885: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499708, Requested 2624. Please try again in 6m42.969599999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 886: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2610. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 887: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2613. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 888: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2624. Please try again in 6m42.7968s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 889: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2610. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 890: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2609. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 891: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2608. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 892: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499707, Requested 2616. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 94%|█████████▍| 902/956 [1:36:47<00:01, 41.76it/s]

Error at row 893: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2634. Please try again in 6m44.352s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 894: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2624. Please try again in 6m42.624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 895: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2610. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 896: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2610. Please try again in 6m40.2048s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 897: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2607. Please try again in 6m39.6864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 898: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2628. Please try again in 6m43.3152s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 899: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2605. Please try again in 6m39.3408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 900: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499706, Requested 2618. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 901: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2602. Please try again in 6m38.6496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 902: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2616. Please try again in 6m41.0688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 95%|█████████▍| 907/956 [1:36:47<00:01, 41.34it/s]

Error at row 903: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2628. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 904: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2607. Please try again in 6m39.5136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 905: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2614. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 906: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2628. Please try again in 6m43.1424s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 907: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499705, Requested 2618. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 908: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2606. Please try again in 6m39.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 909: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2611. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 910: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2614. Please try again in 6m40.5504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 96%|█████████▌| 917/956 [1:36:48<00:00, 40.56it/s]

Error at row 911: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2610. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 912: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2613. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 913: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499704, Requested 2613. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 914: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2618. Please try again in 6m41.0688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 915: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2607. Please try again in 6m39.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 916: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2612. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 917: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2625. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 918: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2610. Please try again in 6m39.6864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 919: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2607. Please try again in 6m39.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 97%|█████████▋| 926/956 [1:36:48<00:00, 37.14it/s]

Error at row 920: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499703, Requested 2621. Please try again in 6m41.5872s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 921: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2611. Please try again in 6m39.6864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 922: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2616. Please try again in 6m40.5504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 923: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2613. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 924: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2624. Please try again in 6m41.9328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 925: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2610. Please try again in 6m39.5136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 926: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499702, Requested 2612. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 927: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2610. Please try again in 6m39.3408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 98%|█████████▊| 934/956 [1:36:48<00:00, 38.32it/s]

Error at row 928: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2609. Please try again in 6m39.168s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 929: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2618. Please try again in 6m40.723199999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 930: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2610. Please try again in 6m39.3408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 931: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2625. Please try again in 6m41.9328s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 932: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2622. Please try again in 6m41.4144s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 933: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499701, Requested 2620. Please try again in 6m41.0688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 934: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2617. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 935: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2614. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 936: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2614. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 937: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2618. Please try again in 6m40.5504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

 99%|█████████▊| 944/956 [1:36:48<00:00, 39.23it/s]

Error at row 938: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2625. Please try again in 6m41.76s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 939: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2614. Please try again in 6m39.8592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 940: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499700, Requested 2608. Please try again in 6m38.8224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 941: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2616. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 942: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2621. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 943: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2604. Please try again in 6m37.9584s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 944: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2630. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 945: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2630. Please try again in 6m42.4512s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 946: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2621. Please try again in 6m40.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

100%|██████████| 956/956 [1:36:49<00:00,  6.08s/it]

Error at row 947: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499699, Requested 2629. Please try again in 6m42.2784s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 948: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2604. Please try again in 6m37.7856s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 949: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2607. Please try again in 6m38.304s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 950: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2655. Please try again in 6m46.5984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 951: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2609. Please try again in 6m38.6496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 952: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2617. Please try again in 6m40.032s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 953: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2660. Please try again in 6m47.4624s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 954: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499698, Requested 2619. Please try again in 6m40.3776s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error at row 955: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.1-8b-instant` in organization `org_01kvxfbcz3e9g9ags6ygx9mrj7` service tier `on_demand` on tokens per day (TPD): Limit 500000, Used 499697, Requested 2611. Please try again in 6m38.8224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

In [ ]:
news_ml_dataset2 = pd.DataFrame(rows)

print(news_ml_dataset2.shape)

news_ml_dataset2.head()

(581, 29)

,commodity,country,date,language,source,url,title_original,title_english,summary,event_type,...,production_drop,production_rise,price_increase,price_decrease,government_policy,weather_event,trade_issue,food_security_issue,export_opportunity_score,confidence
0,Wheat,India,NaN,English,economictimes.indiatimes.com,https://economictimes.indiatimes.com/small-biz...,India lifts total wheat export quota to 5 mill...,India lifts total wheat export quota to 5 mill...,India lifts total wheat export quota to 5 mill...,Export Increase,...,0,0,0,0,1,0,0,0,80,0.9
1,Wheat,India,NaN,English,thehindubusinessline.com,https://www.thehindubusinessline.com/economy/a...,India move to export 5 mt wheat unlikely to im...,India move to export 5 mt wheat unlikely to im...,India move to export 5 mt wheat unlikely to im...,Export Increase,...,0,0,0,0,1,0,0,0,80,0.9
2,Wheat,India,NaN,English,livemint.com,https://www.livemint.com/news/wheat-atta-expor...,"India set to double wheat , flour export quota...","India set to double wheat , flour export quota...","India set to double wheat, flour export quota ...",Export Increase,...,0,0,1,0,1,0,0,0,80,0.9
3,Wheat,India,NaN,English,thehindubusinessline.com,https://www.thehindubusinessline.com/economy/a...,"Geopolitical crisis , weather may help India e...","Geopolitical crisis , weather may help India e...","Geopolitical crisis, weather may help India ex...",Export Increase,...,0,0,0,0,0,1,0,0,80,0.9
4,Wheat,India,NaN,French,zonebourse.com,https://www.zonebourse.com/actualite-bourse/l-...,LInde reprend ses exportations de blé après qu...,"India resumes wheat exports after four years, ...","India resumes wheat exports after four years, ...",Export Increase,...,0,0,1,0,0,0,0,0,20,0.5

In [ ]:
news_ml_dataset2.to_csv(
    "news_ml_dataset6.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully